// <auto-generated />
using System;
using Api.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Infra.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210610090518_Player_Game_Star")]
    partial class Player_Game_Star
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Api.Domain.Entities.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ffbd18-cdb9-45cc-97b0-51e97700bf71"),
                            CreateAt = new DateTime(2021, 6, 10, 9, 5, 16, 975, DateTimeKind.Utc).AddTicks(9122),
                            Name = "Dra Pirilau"
                        },
                        new
                        {
                            Id = new Guid("7cc33300-586e-4be8-9a4d-bd9f01ee9ad8"),
                            CreateAt = new DateTime(2021, 6, 10, 9, 5, 16, 975, DateTimeKind.Utc).AddTicks(9175),
                            Name = "XanaCarnivora"
                        },
                        new
                        {
                            Id = new Guid("cb9e6888-2094-45ee-bc44-37ced33c693a"),
                            CreateAt = new DateTime(2021, 6, 10, 9, 5, 16, 975, DateTimeKind.Utc).AddTicks(9184),
                            Name = "Dapra20comer"
                        },
                        new
                        {
                            Id = new Guid("409b9043-88a4-4e86-9cca-ca1fb0d0d35b"),
                            CreateAt = new DateTime(2021, 6, 10, 9, 5, 16, 975, DateTimeKind.Utc).AddTicks(9193),
                            Name = "Tatycomendo"
                        },
                        new
                        {
                            Id = new Guid("5abca453-d035-4766-a81b-9f73d683a54b"),
                            CreateAt = new DateTime(2021, 6, 10, 9, 5, 16, 975, DateTimeKind.Utc).AddTicks(9200),
                            Name = "Uhpapaichegou"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bda5af3e-0856-41d6-acec-c32660988865"),
                            CreateAt = new DateTime(2021, 6, 10, 9, 5, 16, 971, DateTimeKind.Utc).AddTicks(4808),
                            Email = "user@example.com",
                            Name = "User Padrão",
                            UpdateAt = new DateTime(2021, 6, 10, 9, 5, 16, 971, DateTimeKind.Utc).AddTicks(8533)
                        },
                        new
                        {
                            Id = new Guid("46d1cd7a-c429-46bc-a8c3-26dd7ab60005"),
                            CreateAt = new DateTime(2021, 6, 10, 9, 5, 16, 971, DateTimeKind.Utc).AddTicks(9603),
                            Email = "eskokado@email.com",
                            Name = "Edson Shideki Kokado",
                            UpdateAt = new DateTime(2021, 6, 10, 9, 5, 16, 971, DateTimeKind.Utc).AddTicks(9618)
                        },
                        new
                        {
                            Id = new Guid("c50b091b-f95d-46e0-b1b8-3bf4fdac0db6"),
                            CreateAt = new DateTime(2021, 6, 10, 9, 5, 16, 971, DateTimeKind.Utc).AddTicks(9630),
                            Email = "mariasilva@email.com",
                            Name = "Maria da Silva",
                            UpdateAt = new DateTime(2021, 6, 10, 9, 5, 16, 971, DateTimeKind.Utc).AddTicks(9632)
                        },
                        new
                        {
                            Id = new Guid("146bdcb9-5498-43e1-b132-ab522e599d77"),
                            CreateAt = new DateTime(2021, 6, 10, 9, 5, 16, 971, DateTimeKind.Utc).AddTicks(9638),
                            Email = "josesouza@email.com",
                            Name = "José Souza",
                            UpdateAt = new DateTime(2021, 6, 10, 9, 5, 16, 971, DateTimeKind.Utc).AddTicks(9641)
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.StarEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Stars");
                });

            modelBuilder.Entity("Api.Domain.Entities.StarEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.GameEntity", "Game")
                        .WithMany("Stars")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Domain.Entities.PlayerEntity", "Player")
                        .WithMany("Stars")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Api.Domain.Entities.GameEntity", b =>
                {
                    b.Navigation("Stars");
                });

            modelBuilder.Entity("Api.Domain.Entities.PlayerEntity", b =>
                {
                    b.Navigation("Stars");
                });
#pragma warning restore 612, 618
        }
    }
}
